services:
  gateway:
    build: ./gateway
    ports:
      - 5002:5000
    depends_on:
      - math_py
      - string_rust
  math_py:
    build: ./math_py
    ports:
      - 5001:5000
  string_rust:
    build: ./string_rust
    ports:
      - 5003:5000